/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import Principal.Menu;
import static Principal.VarUser.frmUsr;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.script.ScriptEngineManager;

/**
 *
 * @author Gerry
 */
public class Inicio extends javax.swing.JFrame {

    // variables publicas de botones 
    public static registro frmReg;
    public static Menu frmMen;
    public static LogUser frmLog;
    public static ElimUsuario frmEliU;

    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    // icono de la interfaz 
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLab_usuari = new javax.swing.JLabel();
        btn_salir = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        jLab_usuari1 = new javax.swing.JLabel();
        jLab_usuari2 = new javax.swing.JLabel();
        BTNIMENU = new javax.swing.JButton();
        BTNREGISTRAR = new javax.swing.JButton();
        BTNINICIAR = new javax.swing.JButton();
        BTNELIMINAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLab_usuari.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLab_usuari.setForeground(new java.awt.Color(102, 102, 102));
        jLab_usuari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab_usuari.setText("Bienvenido");

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_2.png"))); // NOI18N
        btn_salir.setToolTipText("");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        btn_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar_2.png"))); // NOI18N
        btn_minimizar.setToolTipText("");
        btn_minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseClicked(evt);
            }
        });

        Icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N
        Icono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Icono.setRequestFocusEnabled(false);

        jLab_usuari1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLab_usuari1.setForeground(new java.awt.Color(102, 102, 102));
        jLab_usuari1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab_usuari1.setText("Proyecto Sistema");

        jLab_usuari2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLab_usuari2.setForeground(new java.awt.Color(102, 102, 102));
        jLab_usuari2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab_usuari2.setText("de Inventario");

        BTNIMENU.setBackground(new java.awt.Color(15, 33, 55));
        BTNIMENU.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNIMENU.setForeground(new java.awt.Color(204, 204, 204));
        BTNIMENU.setText("Menú");
        BTNIMENU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNIMENU.setFocusPainted(false);
        BTNIMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNIMENU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNIMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNIMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNIMENUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNIMENUMouseExited(evt);
            }
        });
        BTNIMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIMENUActionPerformed(evt);
            }
        });

        BTNREGISTRAR.setBackground(new java.awt.Color(15, 33, 55));
        BTNREGISTRAR.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNREGISTRAR.setForeground(new java.awt.Color(204, 204, 204));
        BTNREGISTRAR.setText("Registrar");
        BTNREGISTRAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNREGISTRAR.setFocusPainted(false);
        BTNREGISTRAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNREGISTRAR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNREGISTRAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNREGISTRARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNREGISTRARMouseExited(evt);
            }
        });
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });

        BTNINICIAR.setBackground(new java.awt.Color(15, 33, 55));
        BTNINICIAR.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNINICIAR.setForeground(new java.awt.Color(204, 204, 204));
        BTNINICIAR.setText("Iniciar");
        BTNINICIAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNINICIAR.setFocusPainted(false);
        BTNINICIAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNINICIAR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNINICIARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNINICIARMouseExited(evt);
            }
        });
        BTNINICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNINICIARActionPerformed(evt);
            }
        });

        BTNELIMINAR.setBackground(new java.awt.Color(15, 33, 55));
        BTNELIMINAR.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNELIMINAR.setForeground(new java.awt.Color(204, 204, 204));
        BTNELIMINAR.setText("Editar Usuarios");
        BTNELIMINAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNELIMINAR.setFocusPainted(false);
        BTNELIMINAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNELIMINAR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNELIMINAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNELIMINARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNELIMINARMouseExited(evt);
            }
        });
        BTNELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNELIMINARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLab_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNINICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNIMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLab_usuari1)
                            .addComponent(jLab_usuari2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_minimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLab_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLab_usuari1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLab_usuari2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BTNIMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNINICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // desplazamiento de pantall
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged
    // fin de desplazamiento

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizarMouseClicked

    private void BTNIMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNIMENUMouseEntered
        BTNIMENU.setBackground(new Color(39, 59, 89));
        BTNIMENU.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BTNIMENUMouseEntered

    private void BTNIMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNIMENUMouseExited
        BTNIMENU.setBackground(new Color(15, 33, 55));
        BTNIMENU.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_BTNIMENUMouseExited

    private void BTNIMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIMENUActionPerformed
        if (frmUsr == null) {

        } else {
            if (frmMen == null) {
                // da los valores correspondientes a las variables para que no sean nulas
                frmEliU = new ElimUsuario();
                frmMen = new Menu();
                frmReg = new registro();
                frmLog = new LogUser();

                frmMen.setVisible(true);
            }
        }
    }//GEN-LAST:event_BTNIMENUActionPerformed

    private void BTNREGISTRARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNREGISTRARMouseEntered
        BTNREGISTRAR.setBackground(new Color(39, 59, 89));
        BTNREGISTRAR.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BTNREGISTRARMouseEntered

    private void BTNREGISTRARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNREGISTRARMouseExited
        BTNREGISTRAR.setBackground(new Color(15, 33, 55));
        BTNREGISTRAR.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_BTNREGISTRARMouseExited

    // bloquea los botones al iniciar uno de los formularios, 
    // se activan al cerrar la interza avierta (el metodo se encuentra en la interfaz abierta)
    private void BTNINICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIARActionPerformed
        if (frmUsr == null) {

        } else {
            if (frmLog == null) {

                frmMen = new Menu();
                frmReg = new registro();
                frmLog = new LogUser();
                frmEliU = new ElimUsuario();

                frmLog.setVisible(true);
                this.dispose();
            }
        }

    }//GEN-LAST:event_BTNINICIARActionPerformed

    private void BTNINICIARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNINICIARMouseEntered
        BTNINICIAR.setBackground(new Color(39, 59, 89));
        BTNINICIAR.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BTNINICIARMouseEntered

    private void BTNINICIARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNINICIARMouseExited
        BTNINICIAR.setBackground(new Color(15, 33, 55));
        BTNINICIAR.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_BTNINICIARMouseExited

    private void BTNELIMINARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNELIMINARMouseEntered
        BTNELIMINAR.setBackground(new Color(39, 59, 89));
        BTNELIMINAR.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BTNELIMINARMouseEntered

    private void BTNELIMINARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNELIMINARMouseExited
        BTNELIMINAR.setBackground(new Color(15, 33, 55));
        BTNELIMINAR.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_BTNELIMINARMouseExited

    private void BTNELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNELIMINARActionPerformed
        if (frmUsr == null) {

        } else if (frmEliU == null) {
            //hace los botones inutiles
            frmEliU = new ElimUsuario();
            frmMen = new Menu();
            frmReg = new registro();
            frmLog = new LogUser();

            frmEliU.setVisible(true);

        }
    }//GEN-LAST:event_BTNELIMINARActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        if (frmUsr == null) {

        } else {
            if (frmReg == null) {
                //hace los botones inutiles
                frmEliU = new ElimUsuario();
                frmMen = new Menu();
                frmReg = new registro();
                frmLog = new LogUser();

                frmReg.setVisible(true);
            }
        }
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNELIMINAR;
    private javax.swing.JButton BTNIMENU;
    private javax.swing.JButton BTNINICIAR;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLab_usuari;
    private javax.swing.JLabel jLab_usuari1;
    private javax.swing.JLabel jLab_usuari2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
