package Inicio;

import Principal.Menu;
import Modelos.SqlUsuarios;
import Modelos.columnasTab;
import Principal.VarUser;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
// toma el hash como unused pero si funciona
import static java.util.Objects.hash;
import java.util.TimerTask;
import javax.swing.Timer;

/* @author Gerry */
public class LogUser extends javax.swing.JFrame {

    //Llamada al modelo de las variables de cada tabla y modelo sql de usuarios 
    columnasTab mod = new columnasTab();
    SqlUsuarios modSql = new SqlUsuarios();

    //variables para el bloqueo de espera de sesion
    private Timer t;
    private ActionListener al;
    int frmBtn = 0;
    int reinicio = 0;
    int espera;

    public LogUser() {

        cuentaRegresiva();

        initComponents();
        setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        TXTUSUARIO = new javax.swing.JTextField();
        jLab_usuari = new javax.swing.JLabel();
        jLab_contrase = new javax.swing.JLabel();
        btn_salir = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        TXTERROR = new javax.swing.JLabel();
        BTNINICIAR1 = new javax.swing.JButton();
        TXTCONTRASEÑA = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        TXTUSUARIO.setBackground(new java.awt.Color(255, 255, 255));
        TXTUSUARIO.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTUSUARIO.setForeground(new java.awt.Color(153, 153, 153));
        TXTUSUARIO.setText("Nombre de usuario");
        TXTUSUARIO.setActionCommand("null");
        TXTUSUARIO.setBorder(null);
        TXTUSUARIO.setCaretColor(new java.awt.Color(31, 72, 153));
        TXTUSUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTUSUARIOMouseClicked(evt);
            }
        });

        jLab_usuari.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLab_usuari.setForeground(new java.awt.Color(102, 102, 102));
        jLab_usuari.setText("Usuario:");

        jLab_contrase.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLab_contrase.setForeground(new java.awt.Color(102, 102, 102));
        jLab_contrase.setText("Contraseña:");

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_2.png"))); // NOI18N
        btn_salir.setToolTipText("");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        btn_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar_2.png"))); // NOI18N
        btn_minimizar.setToolTipText("");
        btn_minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseClicked(evt);
            }
        });

        TXTERROR.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTERROR.setForeground(new java.awt.Color(112, 12, 12));

        BTNINICIAR1.setBackground(new java.awt.Color(15, 33, 55));
        BTNINICIAR1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNINICIAR1.setForeground(new java.awt.Color(204, 204, 204));
        BTNINICIAR1.setText("Iniciar");
        BTNINICIAR1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNINICIAR1.setFocusPainted(false);
        BTNINICIAR1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNINICIAR1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNINICIAR1ActionPerformed(evt);
            }
        });

        TXTCONTRASEÑA.setBackground(new java.awt.Color(255, 255, 255));
        TXTCONTRASEÑA.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTCONTRASEÑA.setForeground(new java.awt.Color(153, 153, 153));
        TXTCONTRASEÑA.setText("12345678");
        TXTCONTRASEÑA.setBorder(null);
        TXTCONTRASEÑA.setCaretColor(new java.awt.Color(31, 72, 153));
        TXTCONTRASEÑA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTCONTRASEÑAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLab_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTNINICIAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTCONTRASEÑA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLab_contrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTUSUARIO, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_minimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(jLab_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(TXTUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLab_contrase)
                .addGap(8, 8, 8)
                .addComponent(TXTCONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNINICIAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Seleccion para el movimiento de pantalla
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed
    //Localizacion de la pantalla al mover
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    //Threath para la espera 
    private void cuentaRegresiva() {
        al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //recorrido
                if (reinicio < espera) {
                    reinicio = reinicio + 1;
                    //cuenta regresiva
                    int temp = espera - reinicio;
                    TXTERROR.setText("Esperar " + temp + " segundos");
                } else {
                    t.stop();
                    BTNINICIAR1.setEnabled(true);
                    TXTERROR.setText("");
                    reinicio = 0;
                }
            }
        };
        //tiempo en segundos
        t = new Timer(1000, al);
    }

    //contador de intentos
    private void intento() {
        frmBtn = frmBtn + 1;
        // 3er intento bloqueo
        if (frmBtn == 3) {
            BTNINICIAR1.setEnabled(false);
            if (!t.isRunning()) {
                espera = 30;
                TXTERROR.setText("Esperar " + espera + " segundos");
                t.start();
            }
            //incremento de bloqueos
        } else if (frmBtn > 3) {
            BTNINICIAR1.setEnabled(false);
            if (!t.isRunning()) {
                espera = (int) (10 * (Math.pow(frmBtn - 1, frmBtn - 2)));
                TXTERROR.setText("Esperar " + espera + " segundos");
                t.start();
            }
        }
    }

    private void validarUsuario() {
        // Formato fecha 
        Date date = new Date();
        DateFormat datetime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        mod.setUsuario_responsableENTRADA(TXTUSUARIO.getText());

        String pass = new String(TXTCONTRASEÑA.getPassword());
        if (!TXTUSUARIO.getText().equals("") && !pass.equals("")) {
            String nuevoPass = hash.sha1(pass);

            mod.setUsuarioUSUARIOS(TXTUSUARIO.getText());
            mod.setContraseñaUSUARIOS(nuevoPass);
            mod.setFecha_ingresoUSUARIOS(datetime.format(date));

            if (modSql.login(mod)) {
                this.dispose();

                // Entrada usuario administrador
                if (mod.getId_tipoUSUARIOS() == 1) {
                    Inicio abrir = new Inicio();
                    abrir.setVisible(true);
                    Inicio.frmEliU = null;
                    Inicio.frmMen = null;
                    Inicio.frmReg = null;
                    Inicio.frmLog = null;

                    new VarUser(mod).setVisible(true);

                    // Entrada usuario normal
                } else if (mod.getId_tipoUSUARIOS() == 2) {
                    Menu abrir = new Menu();
                    abrir.setVisible(true);
                    Inicio.frmEliU = null;
                    Inicio.frmMen = null;
                    Inicio.frmReg = null;
                    Inicio.frmLog = null;

                    new VarUser(mod).setVisible(true);
                }
            } else {
                TXTERROR.setText("Datos incorrectos");
            }
        } else {
            TXTERROR.setText("Llenar todos los campos");

        }
    }


    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        // se vuelven a activar los botones de la interfaz Inicio
        Inicio.frmEliU = null;
        Inicio.frmMen = null;
        Inicio.frmReg = null;
        Inicio.frmLog = null;

        if (frmBtn > 3) {
        } else {
            Inicio.frmEliU = null;
            Inicio.frmMen = null;
            Inicio.frmReg = null;
            Inicio.frmLog = null;

            System.exit(0);
        }
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizarMouseClicked

    private void BTNINICIAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIAR1ActionPerformed
        validarUsuario();
        intento();
    }//GEN-LAST:event_BTNINICIAR1ActionPerformed

    private void TXTCONTRASEÑAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCONTRASEÑAMouseClicked
        TXTCONTRASEÑA.setText("");
    }//GEN-LAST:event_TXTCONTRASEÑAMouseClicked

    private void TXTUSUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTUSUARIOMouseClicked
        TXTUSUARIO.setText("");
    }//GEN-LAST:event_TXTUSUARIOMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // se vuelven a activar los botones de la interfaz Inicio
        Inicio.frmMen = null;
        Inicio.frmReg = null;
        Inicio.frmLog = null;
        Inicio.frmEliU = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNINICIAR1;
    private javax.swing.JPasswordField TXTCONTRASEÑA;
    private javax.swing.JLabel TXTERROR;
    private javax.swing.JTextField TXTUSUARIO;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLab_contrase;
    private javax.swing.JLabel jLab_usuari;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private void Start(TimerTask tarea) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
