package Inicio;

import Modelos.SqlUsuarios;
import Modelos.columnasTab;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
//marca el hash como unused, pero si se utiliza
import static java.util.Objects.hash;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/* @author Gerry */
public class registro extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");

    public registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLab_usuari = new javax.swing.JLabel();
        jLab_contrase = new javax.swing.JLabel();
        TXTCONTRASEÑA = new javax.swing.JPasswordField();
        TXTERROR = new javax.swing.JTextField();
        btn_salir = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        jLab_contrase1 = new javax.swing.JLabel();
        TXTCONFIRMAR = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        TXTUSUARIO = new javax.swing.JTextField();
        BTNINICIAR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLab_usuari.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLab_usuari.setForeground(new java.awt.Color(102, 102, 102));
        jLab_usuari.setText("Usuario:");

        jLab_contrase.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLab_contrase.setForeground(new java.awt.Color(102, 102, 102));
        jLab_contrase.setText("Contraseña:");

        TXTCONTRASEÑA.setBackground(new java.awt.Color(255, 255, 255));
        TXTCONTRASEÑA.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTCONTRASEÑA.setForeground(new java.awt.Color(153, 153, 153));
        TXTCONTRASEÑA.setText("12345678");
        TXTCONTRASEÑA.setBorder(null);
        TXTCONTRASEÑA.setCaretColor(new java.awt.Color(31, 72, 153));
        TXTCONTRASEÑA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTCONTRASEÑAMouseClicked(evt);
            }
        });

        TXTERROR.setEditable(false);
        TXTERROR.setBackground(new java.awt.Color(255, 255, 255));
        TXTERROR.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTERROR.setForeground(new java.awt.Color(204, 0, 0));
        TXTERROR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTERROR.setBorder(null);
        TXTERROR.setCaretColor(new java.awt.Color(0, 51, 153));

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_2.png"))); // NOI18N
        btn_salir.setToolTipText("");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_salirMousePressed(evt);
            }
        });

        btn_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar_2.png"))); // NOI18N
        btn_minimizar.setToolTipText("");
        btn_minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseClicked(evt);
            }
        });

        jLab_contrase1.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLab_contrase1.setForeground(new java.awt.Color(102, 102, 102));
        jLab_contrase1.setText("Confirmar");

        TXTCONFIRMAR.setBackground(new java.awt.Color(255, 255, 255));
        TXTCONFIRMAR.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTCONFIRMAR.setForeground(new java.awt.Color(153, 153, 153));
        TXTCONFIRMAR.setText("12345678");
        TXTCONFIRMAR.setBorder(null);
        TXTCONFIRMAR.setCaretColor(new java.awt.Color(31, 72, 153));
        TXTCONFIRMAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTCONFIRMARMouseClicked(evt);
            }
        });

        TXTUSUARIO.setBackground(new java.awt.Color(255, 255, 255));
        TXTUSUARIO.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        TXTUSUARIO.setForeground(new java.awt.Color(153, 153, 153));
        TXTUSUARIO.setText("Nombre de usuario");
        TXTUSUARIO.setActionCommand("null");
        TXTUSUARIO.setBorder(null);
        TXTUSUARIO.setCaretColor(new java.awt.Color(31, 72, 153));
        TXTUSUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTUSUARIOMouseClicked(evt);
            }
        });

        BTNINICIAR1.setBackground(new java.awt.Color(15, 33, 55));
        BTNINICIAR1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNINICIAR1.setForeground(new java.awt.Color(204, 204, 204));
        BTNINICIAR1.setText("Iniciar");
        BTNINICIAR1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNINICIAR1.setFocusPainted(false);
        BTNINICIAR1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNINICIAR1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNINICIAR1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNINICIAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLab_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXTERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_contrase, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_contrase1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLab_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLab_contrase, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(TXTCONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLab_contrase1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTERROR, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNINICIAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // desplazamiento de pantalla 
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed
    //localizacion de pantalla al desplazar
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void registrar() {
        //llama al modelo sql y registros
        SqlUsuarios modSql = new SqlUsuarios();
        columnasTab mod = new columnasTab();

        //guarda usuario para frmUsr
        mod.setUsuario_responsableENTRADA(TXTUSUARIO.getText());

        //guarda datos para registrar
        String pass = String.valueOf(TXTCONTRASEÑA.getPassword());
        String confirmar = String.valueOf(TXTCONFIRMAR.getPassword());

        if (TXTUSUARIO.getText().equals("") || pass.equals("") || confirmar.equals("")) {
            TXTERROR.setText("Completar todos los campos");
        } else {
            if (pass.equals(confirmar)) {
                if (modSql.existeUsuario(TXTUSUARIO.getText()) == 0) {
                    //encriptado de contraseña
                    String nuevoPass = hash.sha1(pass);
                    
                    mod.setUsuarioUSUARIOS(TXTUSUARIO.getText());
                    mod.setContraseñaUSUARIOS(nuevoPass);
                    mod.setId_tipoUSUARIOS(2);
                    
                    if (modSql.registrar(mod)) {
                        TXTERROR.setText("Registro nuevo guardado");
                        limpiar();
                    } else {
                        TXTERROR.setText("Error al guardar");
                    }
                } else {
                    TXTERROR.setText("Usuario ya existente");
                }
            } else {
                TXTERROR.setText("Las contraseñas no coinciden");
            }
        }
    }

    private void limpiar() {
        TXTCONTRASEÑA.setText("");
        TXTCONFIRMAR.setText("");
        TXTUSUARIO.setText("");
    }

    private void btn_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Inicio.frmMen = null;
        Inicio.frmReg = null;
        Inicio.frmLog = null;
        Inicio.frmEliU = null;
    }//GEN-LAST:event_formWindowClosing

    private void BTNINICIAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIAR1ActionPerformed
        registrar();
    }//GEN-LAST:event_BTNINICIAR1ActionPerformed

    private void btn_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMousePressed
        Inicio.frmEliU = null;
        Inicio.frmMen = null;
        Inicio.frmReg = null;
        Inicio.frmLog = null;
        this.setVisible(false);
    }//GEN-LAST:event_btn_salirMousePressed

    private void TXTUSUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTUSUARIOMouseClicked
        TXTUSUARIO.setText("");
    }//GEN-LAST:event_TXTUSUARIOMouseClicked

    private void TXTCONTRASEÑAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCONTRASEÑAMouseClicked
        TXTCONTRASEÑA.setText("");
    }//GEN-LAST:event_TXTCONTRASEÑAMouseClicked

    private void TXTCONFIRMARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCONFIRMARMouseClicked
        TXTCONFIRMAR.setText("");
    }//GEN-LAST:event_TXTCONFIRMARMouseClicked
    int xx, xy;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNINICIAR1;
    private javax.swing.JPasswordField TXTCONFIRMAR;
    private javax.swing.JPasswordField TXTCONTRASEÑA;
    private javax.swing.JTextField TXTERROR;
    private javax.swing.JTextField TXTUSUARIO;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLab_contrase;
    private javax.swing.JLabel jLab_contrase1;
    private javax.swing.JLabel jLab_usuari;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
