package Formularios;

import Modelos.EntradasSQL;
import Modelos.BuscarProductoA;
import Modelos.columnasTab;
import Principal.Menu;
import static Principal.VarUser.frmUsr;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/**
 * @author Gerry
 */
public class Ingresar extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");

    columnasTab us = new columnasTab();
    EntradasSQL e = new EntradasSQL();

    public Ingresar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNINICIAR3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTPRODUCTO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FECHAINGRESO = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        TXTPROVEEDOR = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        PRECIO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        CANTIDAD = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        ESTADOSPRODUCTO = new javax.swing.JComboBox<>();
        BOTONBUSCAR = new javax.swing.JButton();
        TXTERROR = new javax.swing.JLabel();
        BOTONINGRESAR = new javax.swing.JButton();
        TXTCATEGORIA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        BTNINICIAR3.setBackground(new java.awt.Color(15, 33, 55));
        BTNINICIAR3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BTNINICIAR3.setForeground(new java.awt.Color(204, 204, 204));
        BTNINICIAR3.setText("Eliminar");
        BTNINICIAR3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNINICIAR3.setFocusPainted(false);
        BTNINICIAR3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNINICIAR3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNINICIAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNINICIAR3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Producto");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Fecha:");

        TXTPRODUCTO.setBackground(new java.awt.Color(204, 204, 204));
        TXTPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TXTPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        TXTPRODUCTO.setText("Nombre del producto");
        TXTPRODUCTO.setBorder(null);
        TXTPRODUCTO.setCaretColor(new java.awt.Color(0, 51, 153));
        TXTPRODUCTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TXTPRODUCTOMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTPRODUCTOMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_2.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar_2.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Proveedor");

        TXTPROVEEDOR.setBackground(new java.awt.Color(255, 255, 255));
        TXTPROVEEDOR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TXTPROVEEDOR.setForeground(new java.awt.Color(204, 204, 204));
        TXTPROVEEDOR.setText("Nombre del proveedor");
        TXTPROVEEDOR.setBorder(null);
        TXTPROVEEDOR.setCaretColor(new java.awt.Color(0, 51, 153));
        TXTPROVEEDOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TXTPROVEEDORMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTPROVEEDORMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Precio");

        PRECIO.setBackground(new java.awt.Color(255, 255, 255));
        PRECIO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PRECIO.setForeground(new java.awt.Color(204, 204, 204));
        PRECIO.setText("$$$$");
        PRECIO.setBorder(null);
        PRECIO.setCaretColor(new java.awt.Color(0, 51, 153));
        PRECIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PRECIOMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PRECIOMousePressed(evt);
            }
        });
        PRECIO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PRECIOKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Cantidad");

        CANTIDAD.setBackground(new java.awt.Color(255, 255, 255));
        CANTIDAD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CANTIDAD.setForeground(new java.awt.Color(204, 204, 204));
        CANTIDAD.setText("00000");
        CANTIDAD.setBorder(null);
        CANTIDAD.setCaretColor(new java.awt.Color(0, 51, 153));
        CANTIDAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANTIDADMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CANTIDADMousePressed(evt);
            }
        });
        CANTIDAD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CANTIDADKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Estado del producto");

        ESTADOSPRODUCTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fase de Desarrollo", "Fase de Introduccion", "Fase de Crecimiento", "Fase de Madurez", " " }));

        BOTONBUSCAR.setBackground(new java.awt.Color(15, 33, 55));
        BOTONBUSCAR.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BOTONBUSCAR.setForeground(new java.awt.Color(204, 204, 204));
        BOTONBUSCAR.setText("Buscar");
        BOTONBUSCAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BOTONBUSCAR.setFocusPainted(false);
        BOTONBUSCAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BOTONBUSCAR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BOTONBUSCAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BOTONBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONBUSCARActionPerformed(evt);
            }
        });

        BOTONINGRESAR.setBackground(new java.awt.Color(15, 33, 55));
        BOTONINGRESAR.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BOTONINGRESAR.setForeground(new java.awt.Color(204, 204, 204));
        BOTONINGRESAR.setText("Ingresar producto");
        BOTONINGRESAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BOTONINGRESAR.setFocusPainted(false);
        BOTONINGRESAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BOTONINGRESAR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BOTONINGRESAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BOTONINGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONINGRESARActionPerformed(evt);
            }
        });

        TXTCATEGORIA.setBackground(new java.awt.Color(255, 255, 255));
        TXTCATEGORIA.setForeground(new java.awt.Color(204, 204, 204));
        TXTCATEGORIA.setBorder(null);
        TXTCATEGORIA.setCaretColor(new java.awt.Color(0, 51, 153));
        TXTCATEGORIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TXTCATEGORIAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTCATEGORIAMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TXTPROVEEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FECHAINGRESO, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(CANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TXTCATEGORIA, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ESTADOSPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TXTERROR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BOTONINGRESAR, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BOTONBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXTPRODUCTO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTONBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TXTPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(TXTPROVEEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(FECHAINGRESO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(PRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(CANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESTADOSPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTONINGRESAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(418, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(196, 196, 196)))
        );

        ESTADOSPRODUCTO.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // desplazamiento de pantalla
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged
    //fin desplazamiento de pantalla

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu.Elim = null;
        Menu.ElimP = null;
        Menu.Ingr = null;
        Menu.Vent = null;
        Menu.Expor = null;
        Menu.Impor = null;
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BTNINICIAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIAR3ActionPerformed

    }//GEN-LAST:event_BTNINICIAR3ActionPerformed

    //sin usuario no sirve
    private void BOTONINGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONINGRESARActionPerformed
        if (frmUsr == null) {
        } else {
            IngresarProducto();
        }
    }//GEN-LAST:event_BOTONINGRESARActionPerformed

    private void BOTONBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONBUSCARActionPerformed
        Buscar();
    }//GEN-LAST:event_BOTONBUSCARActionPerformed

    // parametros de escritura en precio
    int intn = 0;
    private void PRECIOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PRECIOKeyTyped
        char c = evt.getKeyChar();
        if (c == '.') {
            intn = intn + 1;
            if (intn == 1) {
                if ((c != '.') && (c < '0' || c > '9')) {
                    evt.consume();
                }
            } else if (intn > 1) {
                if (c < '0' || c > '9') {
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_PRECIOKeyTyped

    // parametros de escritura en cantidad 
    private void CANTIDADKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CANTIDADKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_CANTIDADKeyTyped

    //limpiar producto
    private void TXTPRODUCTOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPRODUCTOMouseExited
        if (TXTPRODUCTO.getText().equals("") || TXTPRODUCTO.getText().equals("Nombre del producto")) {
            TXTPRODUCTO.setText("Nombre del producto");
        } else {
        }
    }//GEN-LAST:event_TXTPRODUCTOMouseExited
    private void TXTPRODUCTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPRODUCTOMousePressed
        TXTPRODUCTO.setText("");
    }//GEN-LAST:event_TXTPRODUCTOMousePressed
    //limpiar proveedor
    private void TXTPROVEEDORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPROVEEDORMouseExited
        if (TXTPROVEEDOR.getText().equals("") || TXTPROVEEDOR.getText().equals("Nombre del proveedor")) {
            TXTPROVEEDOR.setText("Nombre del proveedor");
        } else {
        }
    }//GEN-LAST:event_TXTPROVEEDORMouseExited
    private void TXTPROVEEDORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPROVEEDORMousePressed
        TXTPROVEEDOR.setText("");
    }//GEN-LAST:event_TXTPROVEEDORMousePressed
    //limpiar precio
    private void PRECIOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRECIOMouseExited
        if (PRECIO.getText().equals("") || PRECIO.getText().equals("$$$$")) {
            PRECIO.setText("$$$$");
        } else {
        }
    }//GEN-LAST:event_PRECIOMouseExited
    private void PRECIOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRECIOMousePressed
        PRECIO.setText("");
    }//GEN-LAST:event_PRECIOMousePressed
    //limpiar categoria
    private void TXTCATEGORIAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCATEGORIAMousePressed
        TXTCATEGORIA.setText("");
    }//GEN-LAST:event_TXTCATEGORIAMousePressed
    private void TXTCATEGORIAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCATEGORIAMouseExited
        if (TXTCATEGORIA.getText().equals("")) {
            TXTCATEGORIA.setText("");
        } else {
        }
    }//GEN-LAST:event_TXTCATEGORIAMouseExited
    //limpiar cantidad
    private void CANTIDADMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANTIDADMouseExited
        if (CANTIDAD.getText().equals("") || CANTIDAD.getText().equals("00000")) {
            CANTIDAD.setText("00000");
        } else {
        }
    }//GEN-LAST:event_CANTIDADMouseExited
    private void CANTIDADMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANTIDADMousePressed
        CANTIDAD.setText("");
    }//GEN-LAST:event_CANTIDADMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Menu.Elim = null;
        Menu.ElimP = null;
        Menu.Ingr = null;
        Menu.Vent = null;
        Menu.Expor = null;
        Menu.Impor = null;
    }//GEN-LAST:event_formWindowClosing

    private void IngresarProducto() {

        //formato de la fecha
        Date fe = FECHAINGRESO.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String X = df.format(fe);
        System.out.println(X);
        String fecha = String.valueOf(FECHAINGRESO.getDate());

        // si no estan llenados los campos
        if (fecha.equals("null") || TXTPRODUCTO.getText().equals("") || TXTPROVEEDOR.getText().equals("")
                || fecha == "" || PRECIO.getText().equals("")
                || CANTIDAD.getText().equals("") || TXTCATEGORIA.getText().equals("")
                || TXTPRODUCTO.getText().equals("Nombre del producto")
                || TXTPROVEEDOR.getText().equals("Nombre del proveedor")
                || PRECIO.getText().equals("$$$$") || CANTIDAD.getText().equals("00000")) {

            TXTERROR.setText("Completar todos los campos");

        } else {
            //metodo ProductoExistente del modelo EntradasSQL
            if (e.ProductoExistente(TXTPRODUCTO.getText(), TXTPROVEEDOR.getText()) == 0) {

                registros();

                //metodo Entradas del modelo EntradasSQL
                if (e.Entradas(us)) {
                    limpiar();
                } else {
                    TXTERROR.setText("Error al guardar Producto");
                }
                TXTERROR.setText("Producto Guardado");

            } else {

                TXTERROR.setText("Producto Existente");
                registros();

                //metodo Insertar del modelo EntradasSQL
                if (e.Insertar(us)) {
                    limpiar();
                    TXTERROR.setText("Producto Guardado");
                } else {
                    TXTERROR.setText("Error al guardar Producto");
                }

            }

        }
    }

    public void registros() {

        //guardar datos en el modelo columnasTab
        //----------variables
        int numPrecio = Integer.parseInt(PRECIO.getText());
        int numCantidad = Integer.parseInt(CANTIDAD.getText());
        int numSalida = 0;
        int Cantidad2 = us.getCantidadINGRESAR();
        int CTotal = Cantidad2 + numCantidad;
        //----------seters
        us.setProductoINGRESAR(TXTPRODUCTO.getText());
        us.setCategoriaINGRESAR(TXTCATEGORIA.getText());
        us.setSalidaINGRESAR(numSalida);
        us.setEstado_productoINGRESAR(ESTADOSPRODUCTO.getSelectedItem().toString());
        us.setPrecioINGRESAR(numPrecio);
        us.setCantidadINGRESAR(CTotal);
        us.setProveedorCOMPRA(TXTPROVEEDOR.getText());
        us.setFecha_entradaENTRADA(FECHAINGRESO.getDate());
    }

    // limopiar cajas
    public void limpiar() {
        TXTPRODUCTO.setText("");
        TXTPROVEEDOR.setText("");
        CANTIDAD.setText("");
        PRECIO.setText("");
        TXTCATEGORIA.setText("");

    }

    private void Buscar() {

        BuscarProductoA bus = new BuscarProductoA();
        columnasTab usu = new columnasTab();

        //Mandamos el nombre del producto para ser buscado
        usu.setProductoINGRESARB(TXTPRODUCTO.getText());

        // si las cajas estan vacias
        if (TXTPRODUCTO.getText().equals("") || TXTPRODUCTO.getText().equals("Nombre del producto")
                || TXTPROVEEDOR.getText().equals("Nombre del proveedor")) {
            TXTERROR.setText("No ha ingresado el nombre del objeto a buscar");
        } else {

            //metodo InGRESARBUSQUEDA del modelo EntradasSQL
            if (bus.INGRESARBUSQUEDA(usu)) {
                //Iniciamos variables de tipo usuarios para que no sean nulas

                int Precio = usu.getPrecioINGRESARB();
                int Cantidad = usu.getCantidadINGRESARB();

                String Categoria = usu.getCategoriaINGRESARB();
                PRECIO.setText(String.valueOf(Precio));
                CANTIDAD.setText(String.valueOf(Cantidad));
                TXTCATEGORIA.setText(Categoria);
                String Producto = usu.getProductoINGRESARB();

                //Comparaciones
                if (Producto == null) {

                    TXTERROR.setText("Producto No Encontrado");

                } else {
                    TXTERROR.setText("Producto Encontrado");
                }

            } else {
                TXTERROR.setText("Producto No encontrado en Ineventario");
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONBUSCAR;
    private javax.swing.JButton BOTONINGRESAR;
    private javax.swing.JButton BTNINICIAR3;
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JComboBox<String> ESTADOSPRODUCTO;
    private com.toedter.calendar.JDateChooser FECHAINGRESO;
    private javax.swing.JTextField PRECIO;
    private javax.swing.JTextField TXTCATEGORIA;
    private javax.swing.JLabel TXTERROR;
    private javax.swing.JTextField TXTPRODUCTO;
    private javax.swing.JTextField TXTPROVEEDOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
