package Formularios;

import Modelos.columnasTab;
import Modelos.VentasSQL;
import Principal.Menu;
import static Principal.VarUser.frmUsr;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;

public class Venta extends javax.swing.JFrame {



    public Venta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTPRODUCTO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FECHAVENTA = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        TXTCOMPRADOR = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        PRECIOVENTA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        CANTIDADVENTA = new javax.swing.JTextField();
        BOTONVENTA = new javax.swing.JButton();
        TXTERROR = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        TXTPROVEEDOR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Producto");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Fecha:");

        TXTPRODUCTO.setBackground(new java.awt.Color(204, 204, 204));
        TXTPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TXTPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        TXTPRODUCTO.setText("Nombre del producto");
        TXTPRODUCTO.setBorder(null);
        TXTPRODUCTO.setCaretColor(new java.awt.Color(0, 51, 153));
        TXTPRODUCTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TXTPRODUCTOMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTPRODUCTOMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_2.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar_2.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        FECHAVENTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FECHAVENTAMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Comprador");

        TXTCOMPRADOR.setBackground(new java.awt.Color(255, 255, 255));
        TXTCOMPRADOR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TXTCOMPRADOR.setForeground(new java.awt.Color(204, 204, 204));
        TXTCOMPRADOR.setText("Nombre del Comprador");
        TXTCOMPRADOR.setBorder(null);
        TXTCOMPRADOR.setCaretColor(new java.awt.Color(0, 51, 153));
        TXTCOMPRADOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TXTCOMPRADORMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTCOMPRADORMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Precio");

        PRECIOVENTA.setBackground(new java.awt.Color(255, 255, 255));
        PRECIOVENTA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PRECIOVENTA.setForeground(new java.awt.Color(204, 204, 204));
        PRECIOVENTA.setText("$$$$");
        PRECIOVENTA.setBorder(null);
        PRECIOVENTA.setCaretColor(new java.awt.Color(0, 51, 153));
        PRECIOVENTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PRECIOVENTAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PRECIOVENTAMousePressed(evt);
            }
        });
        PRECIOVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRECIOVENTAActionPerformed(evt);
            }
        });
        PRECIOVENTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PRECIOVENTAKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Cantidad");

        CANTIDADVENTA.setBackground(new java.awt.Color(255, 255, 255));
        CANTIDADVENTA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CANTIDADVENTA.setForeground(new java.awt.Color(204, 204, 204));
        CANTIDADVENTA.setText("00000");
        CANTIDADVENTA.setBorder(null);
        CANTIDADVENTA.setCaretColor(new java.awt.Color(0, 51, 153));
        CANTIDADVENTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANTIDADVENTAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CANTIDADVENTAMousePressed(evt);
            }
        });
        CANTIDADVENTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CANTIDADVENTAKeyTyped(evt);
            }
        });

        BOTONVENTA.setBackground(new java.awt.Color(15, 33, 55));
        BOTONVENTA.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BOTONVENTA.setForeground(new java.awt.Color(204, 204, 204));
        BOTONVENTA.setText("Realizar Venta");
        BOTONVENTA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BOTONVENTA.setFocusPainted(false);
        BOTONVENTA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BOTONVENTA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BOTONVENTA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BOTONVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONVENTAActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Proveedor");

        TXTPROVEEDOR.setBackground(new java.awt.Color(204, 204, 204));
        TXTPROVEEDOR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TXTPROVEEDOR.setForeground(new java.awt.Color(102, 102, 102));
        TXTPROVEEDOR.setText("Nombre del proveedor");
        TXTPROVEEDOR.setBorder(null);
        TXTPROVEEDOR.setCaretColor(new java.awt.Color(0, 51, 153));
        TXTPROVEEDOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TXTPROVEEDORMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTPROVEEDORMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FECHAVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PRECIOVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(CANTIDADVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TXTPROVEEDOR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(TXTCOMPRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BOTONVENTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXTERROR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TXTPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TXTPROVEEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(TXTCOMPRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(FECHAVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(PRECIOVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(CANTIDADVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTONVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu.Elim = null;
        Menu.ElimP = null;
        Menu.Ingr = null;
        Menu.Vent = null;
        Menu.Expor = null;
        Menu.Impor = null;
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    //sin usuario no sirve
    private void BOTONVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONVENTAActionPerformed
        if (frmUsr == null) {
        } else {
            RealizarVenta();
        }
    }//GEN-LAST:event_BOTONVENTAActionPerformed

    // parametros de escritura en precio
    int intn = 0;
    private void PRECIOVENTAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PRECIOVENTAKeyTyped
        char c = evt.getKeyChar();
        if (c == '.') {
            intn = intn + 1;
            if (intn == 1) {
                if ((c != '.') && (c < '0' || c > '9')) {
                    evt.consume();
                }
            } else if (intn > 1) {
                if (c < '0' || c > '9') {
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_PRECIOVENTAKeyTyped

    //parametros de escritura en cantidad
    private void CANTIDADVENTAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CANTIDADVENTAKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_CANTIDADVENTAKeyTyped
    // limpiar producto
    private void TXTPRODUCTOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPRODUCTOMouseExited
        if (TXTPRODUCTO.getText().equals("") || TXTPRODUCTO.getText().equals("Nombre del producto")) {
            TXTPRODUCTO.setText("Nombre del producto");
        } else {
        }
    }//GEN-LAST:event_TXTPRODUCTOMouseExited
    private void TXTPRODUCTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPRODUCTOMousePressed
        TXTPRODUCTO.setText("");
    }//GEN-LAST:event_TXTPRODUCTOMousePressed
    // limpiar proveedor
    private void TXTPROVEEDORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPROVEEDORMouseExited
        if (TXTPROVEEDOR.getText().equals("") || TXTPROVEEDOR.getText().equals("Nombre del proveedor")) {
            TXTPROVEEDOR.setText("Nombre del proveedor");
        } else {
        }
    }//GEN-LAST:event_TXTPROVEEDORMouseExited
    private void TXTPROVEEDORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTPROVEEDORMousePressed
        TXTPROVEEDOR.setText("");
    }//GEN-LAST:event_TXTPROVEEDORMousePressed
    // limpiar comprador
    private void TXTCOMPRADORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCOMPRADORMouseExited
        if (TXTCOMPRADOR.getText().equals("") || TXTCOMPRADOR.getText().equals("Nombre del Comprador")) {
            TXTCOMPRADOR.setText("Nombre del Comprador");
        } else {
        }
    }//GEN-LAST:event_TXTCOMPRADORMouseExited
    private void TXTCOMPRADORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCOMPRADORMousePressed
        TXTCOMPRADOR.setText("");
    }//GEN-LAST:event_TXTCOMPRADORMousePressed
    // limpiar precio
    private void PRECIOVENTAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRECIOVENTAMouseExited
        if (PRECIOVENTA.getText().equals("") || PRECIOVENTA.getText().equals("$$$$")) {
            PRECIOVENTA.setText("$$$$");
        } else {
        }
    }//GEN-LAST:event_PRECIOVENTAMouseExited
    private void PRECIOVENTAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRECIOVENTAMousePressed
        PRECIOVENTA.setText("");
    }//GEN-LAST:event_PRECIOVENTAMousePressed
    // limpiar cantidad
    private void CANTIDADVENTAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANTIDADVENTAMouseExited
        if (CANTIDADVENTA.getText().equals("") || CANTIDADVENTA.getText().equals("00000")) {
            CANTIDADVENTA.setText("00000");
        } else {
        }
    }//GEN-LAST:event_CANTIDADVENTAMouseExited
    private void CANTIDADVENTAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANTIDADVENTAMousePressed
        CANTIDADVENTA.setText("");
    }//GEN-LAST:event_CANTIDADVENTAMousePressed

    private void FECHAVENTAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FECHAVENTAMousePressed
        String fecha = String.valueOf(FECHAVENTA.getDate());
        System.out.println(fecha);
    }//GEN-LAST:event_FECHAVENTAMousePressed

    private void PRECIOVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRECIOVENTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRECIOVENTAActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Menu.Elim = null;
        Menu.ElimP = null;
        Menu.Ingr = null;
        Menu.Vent = null;
        Menu.Expor = null;
        Menu.Impor = null;
    }//GEN-LAST:event_formWindowClosing

    public void RealizarVenta() {
        VentasSQL ov = new VentasSQL();
        columnasTab us = new columnasTab();

        String fecha = String.valueOf(FECHAVENTA.getDate());

        // si no estan llenados los campos
        if (fecha.equals("null") || TXTPRODUCTO.getText().equals("") || TXTCOMPRADOR.getText().equals("")
                || fecha.equals("") || PRECIOVENTA.getText().equals("")
                || TXTPRODUCTO.getText().equals("Nombre del producto")
                || TXTPROVEEDOR.getText().equals("Nombre del proveedor")
                || PRECIOVENTA.getText().equals("$$$$") || CANTIDADVENTA.getText().equals("00000")
                || CANTIDADVENTA.getText().equals("")) {

            TXTERROR.setText("Completar todos los campos");

        } else {

            //guardar datos en el modelo columnasTab
            int numC = Integer.parseInt(CANTIDADVENTA.getText());
            int numPrecio = Integer.parseInt(PRECIOVENTA.getText());
            us.setProductoSALIDA(TXTPRODUCTO.getText());
            us.setCompradorVENTA(TXTCOMPRADOR.getText());
            us.setPrecio_ventaVENTA(numPrecio);
            us.setCantidadVENTA(numC);
            us.setFecha_ventaVENTA(FECHAVENTA.getDate());
            us.setProveedorCOMPRA(TXTPROVEEDOR.getText());

            //metodo Venta del modelo VentasSQL
            if (ov.Venta(us)) {
                limpiar();
                TXTERROR.setText("Venta Exitosa");
            } else {
                TXTERROR.setText("Error");
            }
        }
    }

    // limpiar cajas
    public void limpiar() {
        TXTPRODUCTO.setText("");
        TXTPROVEEDOR.setText("");
        PRECIOVENTA.setText("");
        TXTCOMPRADOR.setText("");
        CANTIDADVENTA.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONVENTA;
    private javax.swing.JTextField CANTIDADVENTA;
    private com.toedter.calendar.JDateChooser FECHAVENTA;
    private javax.swing.JTextField PRECIOVENTA;
    private javax.swing.JTextField TXTCOMPRADOR;
    private javax.swing.JLabel TXTERROR;
    private javax.swing.JTextField TXTPRODUCTO;
    private javax.swing.JTextField TXTPROVEEDOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
