package Principal;

import Formularios.Eliminar;
import Formularios.EliminarProducto;
import Formularios.Exportar;
import Formularios.Importar;
import Formularios.Ingresar;
import Formularios.Venta;
import static Principal.VarUser.frmUsr;
import Inicio.Inicio;
import desplazable.Desface;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import static javax.swing.JOptionPane.showMessageDialog;
import tablas.Compras;
import tablas.Entradas;
import tablas.Inventario;
import tablas.Salidas;
import tablas.Ventas;

/* @author master */
public class Menu extends javax.swing.JFrame {

    Desface desplace;

    public static Eliminar Elim;
    public static EliminarProducto ElimP;
    public static Exportar Expor;
    public static Importar Impor;
    public static Ingresar Ingr;
    public static Venta Vent;

    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        desplace = new Desface();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        apertura = new javax.swing.JLabel();
        MenuPlegable = new javax.swing.JPanel();
        Eliminar = new javax.swing.JLabel();
        Desplegar = new javax.swing.JLabel();
        Tablas = new javax.swing.JLabel();
        Ingresar = new javax.swing.JLabel();
        Exportar = new javax.swing.JLabel();
        venta = new javax.swing.JLabel();
        Importar = new javax.swing.JLabel();
        venta1 = new javax.swing.JLabel();
        Separator_ventas = new javax.swing.JSeparator();
        Separator_entradas = new javax.swing.JSeparator();
        Separator_compras = new javax.swing.JSeparator();
        Separator_Salidas = new javax.swing.JSeparator();
        TXTCompras = new javax.swing.JLabel();
        TXTVentas = new javax.swing.JLabel();
        Tabla_Entrdas = new javax.swing.JLabel();
        Tabla_Compras = new javax.swing.JLabel();
        TXTentradas = new javax.swing.JLabel();
        TXTSalidas = new javax.swing.JLabel();
        Tabla_Inventario = new javax.swing.JLabel();
        Tabla_Salidas1 = new javax.swing.JLabel();
        Tabla_Ventas = new javax.swing.JLabel();
        Separator_Inventario = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1080, 700));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        cerrar.setToolTipText("");
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarMousePressed(evt);
            }
        });
        getContentPane().add(cerrar);
        cerrar.setBounds(1030, 0, 40, 50);

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        minimizar.setToolTipText("");
        minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar);
        minimizar.setBounds(1000, 0, 20, 50);

        Icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N
        Icono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Icono.setRequestFocusEnabled(false);
        getContentPane().add(Icono);
        Icono.setBounds(0, 0, 50, 50);

        apertura.setBackground(new java.awt.Color(39, 59, 89));
        apertura.setOpaque(true);
        apertura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                aperturaMouseDragged(evt);
            }
        });
        apertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aperturaMousePressed(evt);
            }
        });
        getContentPane().add(apertura);
        apertura.setBounds(0, 0, 1080, 51);

        MenuPlegable.setBackground(new java.awt.Color(15, 33, 55));
        MenuPlegable.setLayout(null);

        Eliminar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida_2.png"))); // NOI18N
        Eliminar.setText("Salida Producto");
        Eliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Eliminar.setIconTextGap(15);
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarMousePressed(evt);
            }
        });
        MenuPlegable.add(Eliminar);
        Eliminar.setBounds(0, 210, 200, 70);

        Desplegar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Desplegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        Desplegar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        Desplegar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Desplegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesplegarMouseClicked(evt);
            }
        });
        MenuPlegable.add(Desplegar);
        Desplegar.setBounds(0, 0, 200, 70);

        Tablas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tablas.setForeground(new java.awt.Color(255, 255, 255));
        Tablas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Tablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tabla_2.png"))); // NOI18N
        Tablas.setText("Inicio");
        Tablas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        Tablas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tablas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Tablas.setIconTextGap(15);
        Tablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablasMouseClicked(evt);
            }
        });
        MenuPlegable.add(Tablas);
        Tablas.setBounds(0, 70, 200, 70);

        Ingresar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrada_2.png"))); // NOI18N
        Ingresar.setText("Entrada Producto");
        Ingresar.setToolTipText("");
        Ingresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Ingresar.setIconTextGap(15);
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarMousePressed(evt);
            }
        });
        MenuPlegable.add(Ingresar);
        Ingresar.setBounds(0, 140, 200, 70);

        Exportar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Exportar.setForeground(new java.awt.Color(255, 255, 255));
        Exportar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga_2.png"))); // NOI18N
        Exportar.setText("Respaldo    ");
        Exportar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        Exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exportar.setFocusable(false);
        Exportar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Exportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExportarMousePressed(evt);
            }
        });
        MenuPlegable.add(Exportar);
        Exportar.setBounds(0, 520, 200, 70);

        venta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        venta.setForeground(new java.awt.Color(255, 255, 255));
        venta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moneda.png"))); // NOI18N
        venta.setText("Venta de producto    ");
        venta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        venta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        venta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ventaMousePressed(evt);
            }
        });
        MenuPlegable.add(venta);
        venta.setBounds(0, 280, 200, 70);

        Importar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Importar.setForeground(new java.awt.Color(255, 255, 255));
        Importar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imporatar_2.png"))); // NOI18N
        Importar.setText("Importar tablas    ");
        Importar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        Importar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Importar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImportarMousePressed(evt);
            }
        });
        MenuPlegable.add(Importar);
        Importar.setBounds(0, 580, 200, 70);

        venta1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        venta1.setForeground(new java.awt.Color(255, 255, 255));
        venta1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        venta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-eliminar.png"))); // NOI18N
        venta1.setText("Eliminar producto    ");
        venta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        venta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        venta1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        venta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                venta1MousePressed(evt);
            }
        });
        MenuPlegable.add(venta1);
        venta1.setBounds(0, 350, 200, 70);

        getContentPane().add(MenuPlegable);
        MenuPlegable.setBounds(0, 50, 200, 650);

        Separator_ventas.setBackground(new java.awt.Color(51, 51, 51));
        Separator_ventas.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(Separator_ventas);
        Separator_ventas.setBounds(740, 530, 200, 10);

        Separator_entradas.setBackground(new java.awt.Color(51, 51, 51));
        Separator_entradas.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(Separator_entradas);
        Separator_entradas.setBounds(350, 310, 200, 10);

        Separator_compras.setBackground(new java.awt.Color(51, 51, 51));
        Separator_compras.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(Separator_compras);
        Separator_compras.setBounds(350, 530, 200, 10);

        Separator_Salidas.setBackground(new java.awt.Color(51, 51, 51));
        Separator_Salidas.setForeground(new java.awt.Color(51, 51, 51));
        Separator_Salidas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(Separator_Salidas);
        Separator_Salidas.setBounds(740, 310, 200, 10);

        TXTCompras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TXTCompras.setForeground(new java.awt.Color(60, 63, 65));
        TXTCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTCompras.setText("Compras");
        TXTCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TXTCompras);
        TXTCompras.setBounds(350, 500, 200, 30);

        TXTVentas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TXTVentas.setForeground(new java.awt.Color(60, 63, 65));
        TXTVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTVentas.setText("Ventas");
        TXTVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TXTVentas);
        TXTVentas.setBounds(740, 500, 200, 30);

        Tabla_Entrdas.setBackground(new java.awt.Color(51, 51, 51));
        Tabla_Entrdas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tabla_Entrdas.setForeground(new java.awt.Color(255, 255, 255));
        Tabla_Entrdas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tabla_Entrdas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abrir-caja.png"))); // NOI18N
        Tabla_Entrdas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tabla_Entrdas.setOpaque(true);
        Tabla_Entrdas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_EntrdasMousePressed(evt);
            }
        });
        getContentPane().add(Tabla_Entrdas);
        Tabla_Entrdas.setBounds(350, 320, 200, 110);

        Tabla_Compras.setBackground(new java.awt.Color(51, 51, 51));
        Tabla_Compras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tabla_Compras.setForeground(new java.awt.Color(51, 51, 51));
        Tabla_Compras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tabla_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carro-de-la-compra.png"))); // NOI18N
        Tabla_Compras.setText("a");
        Tabla_Compras.setToolTipText("");
        Tabla_Compras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tabla_Compras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Tabla_Compras.setOpaque(true);
        Tabla_Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_ComprasMousePressed(evt);
            }
        });
        getContentPane().add(Tabla_Compras);
        Tabla_Compras.setBounds(350, 540, 200, 110);

        TXTentradas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TXTentradas.setForeground(new java.awt.Color(60, 63, 65));
        TXTentradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTentradas.setText("Entradas");
        TXTentradas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TXTentradas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TXTentradas);
        TXTentradas.setBounds(350, 270, 200, 40);

        TXTSalidas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TXTSalidas.setForeground(new java.awt.Color(60, 63, 65));
        TXTSalidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTSalidas.setText("Salidas");
        TXTSalidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TXTSalidas);
        TXTSalidas.setBounds(740, 270, 200, 40);

        Tabla_Inventario.setBackground(new java.awt.Color(51, 51, 51));
        Tabla_Inventario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tabla_Inventario.setForeground(new java.awt.Color(255, 255, 255));
        Tabla_Inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tabla_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        Tabla_Inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tabla_Inventario.setOpaque(true);
        Tabla_Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_InventarioMousePressed(evt);
            }
        });
        getContentPane().add(Tabla_Inventario);
        Tabla_Inventario.setBounds(540, 120, 200, 110);

        Tabla_Salidas1.setBackground(new java.awt.Color(51, 51, 51));
        Tabla_Salidas1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tabla_Salidas1.setForeground(new java.awt.Color(255, 255, 255));
        Tabla_Salidas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tabla_Salidas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-caja.png"))); // NOI18N
        Tabla_Salidas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tabla_Salidas1.setOpaque(true);
        Tabla_Salidas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_Salidas1MousePressed(evt);
            }
        });
        getContentPane().add(Tabla_Salidas1);
        Tabla_Salidas1.setBounds(740, 320, 200, 110);

        Tabla_Ventas.setBackground(new java.awt.Color(51, 51, 51));
        Tabla_Ventas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Tabla_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        Tabla_Ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tabla_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transferir-dinero.png"))); // NOI18N
        Tabla_Ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tabla_Ventas.setOpaque(true);
        Tabla_Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_VentasMousePressed(evt);
            }
        });
        getContentPane().add(Tabla_Ventas);
        Tabla_Ventas.setBounds(740, 540, 200, 110);

        Separator_Inventario.setBackground(new java.awt.Color(51, 51, 51));
        Separator_Inventario.setForeground(new java.awt.Color(51, 51, 51));
        Separator_Inventario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Separator_Inventario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(Separator_Inventario);
        Separator_Inventario.setBounds(540, 110, 200, 10);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 63, 65));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inventario");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 80, 200, 30);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setOpaque(true);
        getContentPane().add(fondo);
        fondo.setBounds(0, 50, 1080, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //despliegue del menu lateral
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        MenuPlegable.setSize(new Dimension(MenuPlegable.getWidth(), this.getHeight()));
    }//GEN-LAST:event_formComponentResized

    //desplazamiento de pantalla
    int xx, xy;
    private void aperturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aperturaMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_aperturaMousePressed
    // localizacion de pantalla al dezplazar
    private void aperturaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aperturaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_aperturaMouseDragged

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void EliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMousePressed
        if (Elim == null) {
            //hace los botones inutiles
            Elim = new Eliminar();
            ElimP = new EliminarProducto();
            Ingr = new Ingresar();
            Vent = new Venta();
            Expor = new Exportar();
            Impor = new Importar();

            Elim.setVisible(true);
        }
    }//GEN-LAST:event_EliminarMousePressed

    // funconamiento de desplgar menu
    private void DesplegarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesplegarMouseClicked
        if (MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -150, 10, 10);
        } else if (MenuPlegable.getX() == -150) {
            desplace.desplazarDerecha(MenuPlegable, MenuPlegable.getX(), 0, 10, 10);
        }
    }//GEN-LAST:event_DesplegarMouseClicked

    private void TablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablasMouseClicked
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TablasMouseClicked

    private void IngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMousePressed
        if (Ingr == null) {
            //hace los botones inutiles
            Elim = new Eliminar();
            ElimP = new EliminarProducto();
            Ingr = new Ingresar();
            Vent = new Venta();
            Expor = new Exportar();
            Impor = new Importar();

            Ingr.setVisible(true);
        }
    }//GEN-LAST:event_IngresarMousePressed

    private void ExportarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportarMousePressed
        if (frmUsr.equals("Admin")) {

            if (Expor == null) {
                //hace los botones inutiles
                Elim = new Eliminar();
                ElimP = new EliminarProducto();
                Ingr = new Ingresar();
                Vent = new Venta();
                Expor = new Exportar();
                Impor = new Importar();

                Expor.setVisible(true);
            }
        } else {
            showMessageDialog(null, "Solo el administrador puede usar esta opcion");
        }

    }//GEN-LAST:event_ExportarMousePressed

    private void ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMousePressed
        if (Vent == null) {
            //hace los botones inutiles
            Elim = new Eliminar();
            ElimP = new EliminarProducto();
            Ingr = new Ingresar();
            Vent = new Venta();
            Expor = new Exportar();
            Impor = new Importar();

            Vent.setVisible(true);
        }
    }//GEN-LAST:event_ventaMousePressed

    private void ImportarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportarMousePressed
        if (frmUsr.equals("Admin")) {
            if (Impor == null) {
                //hace los botones inutiles
                Elim = new Eliminar();
                ElimP = new EliminarProducto();
                Ingr = new Ingresar();
                Vent = new Venta();
                Expor = new Exportar();
                Impor = new Importar();

                Impor.setVisible(true);
            }
        } else {
            showMessageDialog(null, "Solo el administrador puede usar esta opcion");
        }

    }//GEN-LAST:event_ImportarMousePressed

    private void Tabla_EntrdasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_EntrdasMousePressed
        Entradas abrir = new Entradas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Tabla_EntrdasMousePressed

    private void Tabla_ComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ComprasMousePressed
        Compras abrir = new Compras();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabla_ComprasMousePressed

    private void Tabla_InventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_InventarioMousePressed
        Inventario abrir = new Inventario();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Tabla_InventarioMousePressed

    private void Tabla_Salidas1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_Salidas1MousePressed
        Salidas abrir = new Salidas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Tabla_Salidas1MousePressed

    private void Tabla_VentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_VentasMousePressed
        Ventas abrir = new Ventas();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabla_VentasMousePressed
    private void cerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMousePressed
        // se vuelven a activar los botones de la interfaz Inicio

        if (frmUsr == null) {
            System.exit(0);

        } else if (frmUsr.equals("Admin")) {
            //botones de interfaz Inicio
            Inicio.frmEliU = null;
            Inicio.frmMen = null;
            Inicio.frmReg = null;
            Inicio.frmLog = null;

            this.setVisible(false);

        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_cerrarMousePressed
    // se vuelven a activar los botones de la interfaz Inicio
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (frmUsr.equals("Admin")) {
            //botones de interfaz inicio
            Inicio.frmEliU = null;
            Inicio.frmMen = null;
            Inicio.frmReg = null;
            Inicio.frmLog = null;
        } else {
        }
    }//GEN-LAST:event_formWindowClosing

    private void venta1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venta1MousePressed

        if (frmUsr.equals("Admin")) {
            if (ElimP == null) {
                //hace los botones inutiles
                Elim = new Eliminar();
                ElimP = new EliminarProducto();
                Ingr = new Ingresar();
                Vent = new Venta();
                Expor = new Exportar();
                Impor = new Importar();

                ElimP.setVisible(true);
            }

        } else {
            showMessageDialog(null, "Solo el administrador puede usar esta opcion");

        }

    }//GEN-LAST:event_venta1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desplegar;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Exportar;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel Importar;
    private javax.swing.JLabel Ingresar;
    private javax.swing.JPanel MenuPlegable;
    private javax.swing.JSeparator Separator_Inventario;
    private javax.swing.JSeparator Separator_Salidas;
    private javax.swing.JSeparator Separator_compras;
    private javax.swing.JSeparator Separator_entradas;
    private javax.swing.JSeparator Separator_ventas;
    private javax.swing.JLabel TXTCompras;
    private javax.swing.JLabel TXTSalidas;
    private javax.swing.JLabel TXTVentas;
    private javax.swing.JLabel TXTentradas;
    private javax.swing.JLabel Tabla_Compras;
    private javax.swing.JLabel Tabla_Entrdas;
    private javax.swing.JLabel Tabla_Inventario;
    private javax.swing.JLabel Tabla_Salidas1;
    private javax.swing.JLabel Tabla_Ventas;
    private javax.swing.JLabel Tablas;
    private javax.swing.JLabel apertura;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel venta;
    private javax.swing.JLabel venta1;
    // End of variables declaration//GEN-END:variables
}
